name: Build print-args

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - name: Build
      run: make build
    - uses: actions/upload-artifact@v4.6.2
      name: Upload artifact
      with:
        name: print-args
        path: bin/print-args
